# Generated by Django 5.2.12 on 2026-04-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profissionais", "0002_profissional_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="profissional",
            name="acessos_modulos",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
