# Generated by Django 5.2.12 on 2026-04-07 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_passwordrecoverycode'),
        ('empresas', '0004_empresa_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_session_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('object_type', models.CharField(choices=[('agendamento', 'Agendamento'), ('plano', 'Plano mensal')], max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('succeeded', 'Sucesso'), ('failed', 'Falha'), ('canceled', 'Cancelado'), ('refunded', 'Reembolsado')], default='pending', max_length=20)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('webhook_received_at', models.DateTimeField(blank=True, null=True)),
                ('webhook_data', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('refund_reason', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stripe_transactions', to='empresas.empresa')),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['empresa', 'status'], name='core_stripe_empresa_faf8d7_idx'), models.Index(fields=['object_type', 'object_id'], name='core_stripe_object__f3bb73_idx')],
            },
        ),
    ]
