# Generated by Django 5.2.12 on 2026-04-09 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_stripetransaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StripeTransaction',
        ),
    ]
