# Generated by Django 5.2.12 on 2026-04-10 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0010_alter_agendamento_status'),
        ('core', '0005_stripewebhookevent'),
        ('empresas', '0007_empresa_portal_token'),
        ('pessoa', '0003_pessoa_portal_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteportalpreferencia',
            name='receber_lembrete_24h',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clienteportalpreferencia',
            name='receber_lembrete_2h',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ClienteFidelidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos_disponiveis', models.PositiveIntegerField(default=0)),
                ('pontos_totais', models.PositiveIntegerField(default=0)),
                ('codigo_indicacao', models.CharField(blank=True, max_length=24)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fidelidade', to='pessoa.pessoa')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_fidelidade', to='empresas.empresa')),
                ('indicador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicacoes_realizadas', to='pessoa.pessoa')),
            ],
            options={
                'unique_together': {('empresa', 'cliente')},
            },
        ),
        migrations.CreateModel(
            name='FidelidadeMovimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('agendamento', 'Agendamento'), ('produto', 'Produto'), ('indicacao', 'Indicacao'), ('ajuste', 'Ajuste')], max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('pontos', models.IntegerField()),
                ('referencia_id', models.CharField(blank=True, max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente_fidelidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos', to='core.clientefidelidade')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='NPSResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveSmallIntegerField()),
                ('comentario', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('agendamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nps_respostas', to='agendamentos.agendamento')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pessoa.pessoa')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nps_respostas', to='empresas.empresa')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ProgramaFidelidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=False)),
                ('pontos_por_real', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('multiplicador_indicacao', models.DecimalField(decimal_places=2, default=1.5, max_digits=6)),
                ('pontos_bonus_indicacao', models.PositiveIntegerField(default=50)),
                ('ticket_minimo_indicacao', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='programa_fidelidade', to='empresas.empresa')),
            ],
        ),
    ]
