# Generated by Django 5.2.12 on 2026-04-10 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_clienteportalpreferencia_receber_lembrete_24h_and_more'),
        ('empresas', '0007_empresa_portal_token'),
        ('pessoa', '0003_pessoa_portal_password_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=120)),
                ('entidade', models.CharField(blank=True, max_length=80)),
                ('entidade_id', models.CharField(blank=True, max_length=64)),
                ('detalhes', models.JSONField(blank=True, default=dict)),
                ('endereco_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ator_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='pessoa.pessoa')),
                ('ator_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='empresas.empresa')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
