# Generated by Django 5.2.12 on 2026-04-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='estoque_reservado',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade reservada em agendamentos não pagos'),
        ),
    ]
