# Generated by Django 5.2.12 on 2026-04-09 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_empresa_whatsapp'),
        ('pessoa', '0003_pessoa_portal_password_and_more'),
        ('produtos', '0002_produto_estoque_reservado'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome_avulso', models.CharField(blank=True, help_text='Nome do cliente se não cadastrado', max_length=255)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('custo', models.DecimalField(decimal_places=2, help_text='Custo de aquisição do produto', max_digits=10)),
                ('valor_mercado', models.DecimalField(decimal_places=2, help_text='Valor de referência de mercado', max_digits=10)),
                ('valor_final', models.DecimalField(decimal_places=2, help_text='Valor cobrado na venda', max_digits=10)),
                ('metodo_pagamento', models.CharField(blank=True, choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('cartao_debito', 'Cartão de Débito'), ('cartao_credito', 'Cartão de Crédito'), ('transferencia', 'Transferência'), ('fiado', 'Fiado')], max_length=20)),
                ('data_venda', models.DateField(help_text='Data em que a venda foi realizada')),
                ('data_recebimento', models.DateField(blank=True, help_text='Data em que o pagamento foi recebido', null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_produtos', to='pessoa.pessoa')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas_produtos', to='empresas.empresa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='produtos.produto')),
            ],
            options={
                'ordering': ['-data_venda', '-criado_em'],
            },
        ),
    ]
