# Generated by Django 5.2.12 on 2026-04-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_vendaproduto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendaproduto',
            old_name='data_recebimento',
            new_name='data_pagamento',
        ),
        migrations.RenameField(
            model_name='vendaproduto',
            old_name='valor_final',
            new_name='valor_venda',
        ),
        migrations.RemoveField(
            model_name='vendaproduto',
            name='custo',
        ),
        migrations.RemoveField(
            model_name='vendaproduto',
            name='metodo_pagamento',
        ),
        migrations.RemoveField(
            model_name='vendaproduto',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='vendaproduto',
            name='valor_mercado',
        ),
        migrations.AddField(
            model_name='produto',
            name='custo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Custo operacional total do produto', max_digits=10),
        ),
        migrations.AddField(
            model_name='produto',
            name='valor_compra',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor pago na compra/aquisição do produto', max_digits=10),
        ),
        migrations.AddField(
            model_name='produto',
            name='valor_venda',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor cobrado na venda ao cliente', max_digits=10),
        ),
    ]
