# Generated by Django 5.2.12 on 2026-04-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0004_rename_data_recebimento_vendaproduto_data_pagamento_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="foto",
            field=models.ImageField(blank=True, upload_to="produtos/"),
        ),
    ]
