# Generated by Django 5.2.12 on 2026-04-10 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamentos", "0009_agendalock_slothold"),
        ("produtos", "0005_alter_produto_foto"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendaproduto",
            name="agendamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vendas_produtos",
                to="agendamentos.agendamento",
            ),
        ),
        migrations.AddField(
            model_name="vendaproduto",
            name="data_entrega",
            field=models.DateField(
                blank=True,
                help_text="Data prevista para retirada/entrega do produto",
                null=True,
            ),
        ),
    ]
