from django.urls import path
from . import views

urlpatterns = [
    path('healthz/', views.healthz, name='healthz'),
    path('readyz/', views.readyz, name='readyz'),
    path('stripe/webhook/', views.stripe_webhook, name='stripe_webhook'),
    path('service-worker.js', views.service_worker_js, name='service_worker_js'),
    path('accounts/recuperar-senha/', views.password_recovery_request, name='password_recovery_request'),
    path('accounts/recuperar-senha/confirmar/', views.password_recovery_confirm, name='password_recovery_confirm'),
    path('accounts/login-redirect/', views.login_redirect, name='login_redirect'),
    path('', views.home, name='home'),
    path('cliente/', views.home, name='cliente_home'),
    path('cliente/empresa/<uuid:portal_token>/', views.empresa_detail, name='cliente_empresa'),
    path('cliente/empresa/<uuid:portal_token>/catalogo/', views.empresa_catalogo, name='cliente_catalogo'),
    path('cliente/empresa/<uuid:portal_token>/loja/', views.loja_produtos, name='loja_produtos'),
    path('cliente/empresa/<uuid:portal_token>/api/carrinho/listar/', views.api_carrinho_listar, name='api_carrinho_listar'),
    path('cliente/empresa/<uuid:portal_token>/api/carrinho/adicionar/', views.api_carrinho_adicionar, name='api_carrinho_adicionar'),
    path('cliente/empresa/<uuid:portal_token>/api/carrinho/remover/', views.api_carrinho_remover, name='api_carrinho_remover'),
    path('cliente/empresa/<uuid:portal_token>/api/carrinho/atualizar/', views.api_carrinho_atualizar, name='api_carrinho_atualizar'),
    path('cliente/empresa/<uuid:portal_token>/minha-conta/', views.cliente_minha_conta, name='cliente_minha_conta'),
    path('cliente/empresa/<uuid:portal_token>/horarios/', views.available_slots_api, name='cliente_horarios'),
    path('cliente/empresa/<uuid:portal_token>/api/horarios/hold/', views.slot_hold_api, name='cliente_slot_hold_api'),
    path('cliente/empresa/<uuid:portal_token>/api/portal/login-senha/', views.portal_password_login_api, name='portal_password_login_api'),
    path('cliente/empresa/<uuid:portal_token>/api/portal/enviar-otp/', views.portal_enviar_otp_api, name='portal_enviar_otp_api'),
    path('cliente/empresa/<uuid:portal_token>/api/portal/validar-otp/', views.portal_validar_otp_api, name='portal_validar_otp_api'),
    path('cliente/empresa/<uuid:portal_token>/api/portal/logout/', views.portal_logout_api, name='portal_logout_api'),
    path('cliente/empresa/<uuid:portal_token>/api/agendamentos/', views.cliente_agendamentos_api, name='cliente_agendamentos_api'),
    path('cliente/empresa/<uuid:portal_token>/api/agendamentos/<int:agendamento_id>/cancelar/', views.cliente_agendamento_cancelar_api, name='cliente_agendamento_cancelar_api'),
    path('cliente/empresa/<uuid:portal_token>/api/agendamentos/<int:agendamento_id>/remarcar/', views.cliente_agendamento_remarcar_api, name='cliente_agendamento_remarcar_api'),
]
