# Generated by Django 5.2.12 on 2026-04-06 00:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamentos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pagamento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("metodo", models.CharField(choices=[("pix", "Pix"), ("cartao", "Cartao")], default="pix", max_length=20)),
                ("status", models.CharField(choices=[("pendente", "Pendente"), ("pago", "Pago"), ("cancelado", "Cancelado"), ("expirado", "Expirado")], default="pendente", max_length=20)),
                ("referencia_publica", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("referencia_pagamento", models.CharField(blank=True, max_length=40, unique=True)),
                ("codigo_pix", models.CharField(blank=True, max_length=255)),
                ("detalhes", models.CharField(blank=True, max_length=255)),
                ("pago_em", models.DateTimeField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("agendamento", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="pagamento", to="agendamentos.agendamento")),
                ("cliente", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="pessoa.pessoa")),
                ("empresa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="empresas.empresa")),
            ],
            options={
                "ordering": ["-criado_em"],
            },
        ),
    ]
