# Generated by Django 5.2.12 on 2026-04-07 00:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_pagamento'),
        ('empresas', '0001_initial'),
        ('pessoa', '0001_initial'),
        ('profissionais', '0001_initial'),
        ('servicos', '0002_servico_cor_alter_servico_nome_alter_servico_preco'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.DateField()),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terca-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sabado'), (6, 'Domingo')])),
                ('hora', models.TimeField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('ativo', 'Ativo'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('pagamento_status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado'), ('expirado', 'Expirado')], default='pendente', max_length=20)),
                ('metodo_pagamento', models.CharField(blank=True, choices=[('pix', 'Pix'), ('cartao', 'Cartao')], max_length=20)),
                ('valor_mensal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantidade_encontros', models.PositiveIntegerField(default=0)),
                ('referencia_publica', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('referencia_pagamento', models.CharField(blank=True, max_length=40, unique=True)),
                ('codigo_pix', models.CharField(blank=True, max_length=255)),
                ('detalhes_pagamento', models.CharField(blank=True, max_length=255)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoa.pessoa')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profissionais.profissional')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.servico')),
            ],
            options={
                'ordering': ['-mes_referencia', '-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='agendamento',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='agendamentos.planomensal'),
        ),
    ]
