# Generated by Django 5.2.12 on 2026-04-07 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_planomensal_agendamento_plano'),
        ('empresas', '0001_initial'),
        ('produtos', '0002_produto_estoque_reservado'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagamento_status', models.CharField(choices=[('reservado', 'Reservado'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='reservado', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='agendamentos.agendamento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='produtos.produto')),
            ],
            options={
                'ordering': ['criado_em'],
                'unique_together': {('agendamento', 'produto')},
            },
        ),
    ]
