# Generated by Django 5.2.12 on 2026-04-07 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0004_agendamentoproduto'),
        ('profissionais', '0002_profissional_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('mensagem', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_profissional', to='agendamentos.agendamento')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='profissionais.profissional')),
            ],
            options={
                'ordering': ['-criada_em'],
            },
        ),
    ]
