# Generated by Django 5.2.12 on 2026-04-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0005_notificacaoprofissional'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe Customer ID (optional for guests)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, help_text='Stripe Payment Intent ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='stripe_session_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stripe Checkout Session ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='stripe_synced_at',
            field=models.DateTimeField(blank=True, help_text='Last sync with Stripe', null=True),
        ),
        migrations.AddField(
            model_name='planomensal',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe Customer ID (optional for guests)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='planomensal',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, help_text='Stripe Payment Intent ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='planomensal',
            name='stripe_session_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stripe Checkout Session ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='planomensal',
            name='stripe_synced_at',
            field=models.DateTimeField(blank=True, help_text='Last sync with Stripe', null=True),
        ),
    ]
