# Generated by Django 5.2.12 on 2026-04-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0006_pagamento_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='observacoes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='planomensal',
            name='observacoes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
