# Generated by Django 5.2.12 on 2026-04-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0007_alter_agendamento_observacoes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='agendamento',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='forma_pagamento',
        ),
        migrations.RemoveField(
            model_name='planomensal',
            name='codigo_pix',
        ),
        migrations.RemoveField(
            model_name='planomensal',
            name='referencia_pagamento',
        ),
        migrations.RemoveField(
            model_name='planomensal',
            name='referencia_publica',
        ),
        migrations.RemoveField(
            model_name='planomensal',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='planomensal',
            name='stripe_payment_intent_id',
        ),
        migrations.RemoveField(
            model_name='planomensal',
            name='stripe_session_id',
        ),
        migrations.RemoveField(
            model_name='planomensal',
            name='stripe_synced_at',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='metodo_pagamento',
            field=models.CharField(blank=True, choices=[('pix', 'Pix'), ('cartao', 'Cartão'), ('dinheiro', 'Dinheiro'), ('transferencia', 'Transferência')], max_length=20),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='pagamento_status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
        migrations.DeleteModel(
            name='AgendamentoProduto',
        ),
        migrations.DeleteModel(
            name='Pagamento',
        ),
    ]
