# Generated by Django 5.2.12 on 2026-04-09 21:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0008_remove_pagamento_agendamento_and_more'),
        ('empresas', '0004_empresa_whatsapp'),
        ('profissionais', '0002_profissional_usuario'),
        ('servicos', '0002_servico_cor_alter_servico_nome_alter_servico_preco'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profissionais.profissional')),
            ],
            options={
                'unique_together': {('empresa', 'profissional', 'data')},
            },
        ),
        migrations.CreateModel(
            name='SlotHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('consumed', 'Consumido'), ('released', 'Liberado'), ('expired', 'Expirado')], db_index=True, default='active', max_length=20)),
                ('reservado_ate', models.DateTimeField()),
                ('session_key', models.CharField(blank=True, max_length=120)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profissionais.profissional')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.servico')),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['empresa', 'profissional', 'data', 'status'], name='agendamento_empresa_c0e0a4_idx')],
            },
        ),
    ]
