# Generated by Django 5.2.12 on 2026-04-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0009_agendalock_slothold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('finalizado', 'Finalizado'), ('no_show', 'Nao compareceu')], default='pendente', max_length=20),
        ),
    ]
