# Generated by Django 5.2.12 on 2026-04-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0002_alter_pessoa_data_nascimento_alter_pessoa_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='portal_password',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='portal_password_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
