# Generated by Django 5.2.12 on 2026-04-07 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='limite_profissionais',
            field=models.PositiveSmallIntegerField(default=5, help_text='Limite comercial de profissionais ativos para esta empresa.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='empresa',
            name='plano',
            field=models.CharField(choices=[('start', 'Start (ate 5 funcionarios)')], default='start', max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='valor_mensal',
            field=models.DecimalField(decimal_places=2, default=147, max_digits=10),
        ),
    ]
