# Generated by Django 5.2.12 on 2026-04-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_limite_profissionais_empresa_plano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='plano',
            field=models.CharField(choices=[('solo', 'Solo (1 funcionario com acesso)'), ('start', 'Start (ate 5 funcionarios)'), ('admin_only', 'Gestao interna (somente administrador)')], default='start', max_length=20),
        ),
    ]
