# Generated by Django 5.2.12 on 2026-04-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_alter_empresa_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
