# Generated by Django 5.2.12 on 2026-04-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_empresa_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cor_primaria',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cor_secundaria',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='empresa',
            name='logo_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
