# Generated by Django 5.2.12 on 2026-04-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0005_empresa_cor_primaria_empresa_cor_secundaria_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="empresas/logos/"),
        ),
    ]
