# Generated by Django 5.2.12 on 2026-04-10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0006_empresa_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="portal_token",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
